pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = uri("https://fabricmc.net")
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("net.fabricmc.loom") version "1.7-SNAPSHOT" apply false
}

rootProject.name = "ChickClient"
