name: Build Chick Client
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v4
        with:
          path: user-code

      - name: Checkout Fabric Template Base
        uses: actions/checkout@v4
        with:
          repository: FabricMC/fabric-example-mod
          path: fabric-template

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Inject Your Code Into Template
        run: |
          # 1. Limpa o codigo original do template
          rm -rf fabric-template/src/main/java/net/fabricmc/example/*
          rm -f fabric-template/src/main/resources/fabric.mod.json
          
          # 2. Encontra o SEU codigo e joga na pasta certa do template
          find user-code/ -name "ChickClientPvpMod.java" -exec cp {} fabric-template/src/main/java/net/fabricmc/example/ \;
          find user-code/ -name "fabric.mod.json" -exec cp {} fabric-template/src/main/resources/ \;

      - name: Build Mod with Gradle
        run: |
          cd fabric-template
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Upload Compiled Jar
        uses: actions/upload-artifact@v4
        with:
          name: ChickClient-Jar
          path: fabric-template/build/libs/*.jar
